<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>

		<TargetFramework>net48</TargetFramework>
		<EnableDynamicLoading>true</EnableDynamicLoading>
		<TargetExt>.rhp</TargetExt>
		<NoWarn>NU1701</NoWarn>
		<LangVersion>7.0</LangVersion>
		<RestoreEnabled>false</RestoreEnabled>
		<UseWindowsForms>false</UseWindowsForms>
	</PropertyGroup>


	<PropertyGroup>
		
		<Version>1.4.8.4</Version>
		<AssemblyVersion>$(Version)</AssemblyVersion>
		<Title>MyChangeTools</Title>
		<Authors>Whysiki</Authors>
		<Company>Whysiki Personal</Company>
		<Description>Somw plug-ins for change and morph geometries</Description>
	</PropertyGroup>

	<PropertyGroup Condition="'$(Configuration)|$(TargetFramework)|$(Platform)'=='Debug|net7.0|AnyCPU'">
		<TreatWarningsAsErrors>True</TreatWarningsAsErrors>
	</PropertyGroup>

	<PropertyGroup Condition="'$(Configuration)|$(TargetFramework)|$(Platform)'=='Debug|net48|AnyCPU'">
		<TreatWarningsAsErrors>True</TreatWarningsAsErrors>
	</PropertyGroup>

	<PropertyGroup Condition="'$(Configuration)|$(TargetFramework)|$(Platform)'=='Release|net7.0|AnyCPU'">
		<TreatWarningsAsErrors>True</TreatWarningsAsErrors>
	</PropertyGroup>

	<PropertyGroup Condition="'$(Configuration)|$(TargetFramework)|$(Platform)'=='Release|net48|AnyCPU'">
		<TreatWarningsAsErrors>True</TreatWarningsAsErrors>
	</PropertyGroup>

	<ItemGroup>
		<Reference Include="MathNet.Numerics">
			<HintPath>MyLib/MathNet.Numerics.dll</HintPath>
		</Reference>

		<Reference Include="System.Numerics.Vectors">
			<HintPath>MyLib/System.Numerics.Vectors.dll</HintPath>
		</Reference>
	</ItemGroup>

	<ItemGroup>

		<Reference Include="RhinoCommon">
			<HintPath>C:\Program Files\Rhino 7\System\RhinoCommon.dll</HintPath>
			<Private>false</Private>
		</Reference>

		<Reference Include="Eto">
			<HintPath>C:\Program Files\Rhino 7\System\Eto.dll</HintPath>
			<Private>false</Private>
		</Reference>
		 
	</ItemGroup>

	<ItemGroup>
	  <Folder Include="commands\RbfDeform\Panel\" />
	</ItemGroup>

	<PropertyGroup>
		<CopyLocalLockFileAssemblies>true</CopyLocalLockFileAssemblies>
	</PropertyGroup>


</Project>
