<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
    
		<TargetFrameworks>net48</TargetFrameworks>
		<EnableDynamicLoading>true</EnableDynamicLoading>
		<TargetExt>.rhp</TargetExt>
		<NoWarn>NU1701</NoWarn>
		<LangVersion>7.0</LangVersion>
	</PropertyGroup>

	<PropertyGroup>
		<Version>1.0</Version>
		<Title>MyRhinoSelectTools</Title>
		<Company>MyRhinoSelectTools Authors</Company>
		<Description>Description of MyRhinoSelectTools</Description>
	</PropertyGroup>

	<ItemGroup>
		<Reference Include="RhinoCommon">
			<HintPath>C:\Program Files\Rhino 7\System\RhinoCommon.dll</HintPath>
			<Private>false</Private>
		</Reference>
	</ItemGroup>

	<PropertyGroup>
		<CopyLocalLockFileAssemblies>true</CopyLocalLockFileAssemblies>
	</PropertyGroup>


</Project>
